//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Case_37.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Descrition { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Photo { get; set; }
        public int IdCategory { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
